version: '3.8'

services:
  react-app:
    image: node:18 
    container_name: react_vite_app
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app 
      - /usr/src/app/node_modules 
    ports:
      - "3000:5173" 
    command: sh -c "npm install && npm run dev"
    restart: unless-stopped
