version: '3.8'

services:
  mqtt-client:
    build: .
    container_name: mqtt-client-receiver
    ports:
      - "3001:3001"
    restart: unless-stopped
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    restart: unless-stopped
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: seeit_db
      MONGO_INITDB_ROOT_USERNAME: seeit2024
      MONGO_INITDB_ROOT_PASSWORD: seeit2024
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: