version: '3.8'

services:
  mqtt-client:
    build: .
    image: mqtt-script-node-receiver
    container_name: mqtt-client-receiver
    ports:
      - "3001:3001"
    restart: unless-stopped

  db:
    image: postgres:latest
    restart: unless-stopped
    container_name: postgres_db
    environment:
      POSTGRES_DB: mqtt_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: