version: '3.8'

services:
  server:
    build: .
    container_name: server
    ports:
      - "5001:5001"
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"  
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db 

volumes:
  mongodb_data:
    driver: local
